spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/{db name}
    username: {username}
    password: {password}
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

  redis:
    host: localhost
    port: 6379

  # rabbitMQ 관련
  rabbitmq:
    host: {rabbitmq ip}
    port: 5672
    username: {username}
    password: {password}
    virtual-host: {vhost}

# HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
# Secret 값은 특정 문자열을 Base64 로 인코딩한 값 사용 (아래 명령어를 터미널에 쳐보면 그대로 나옴)
# $ echo '{특정 문자열}' | base64
jwt:
  secret:

# firebase json path
firebaseJsonPath:
  path:

# Photon AppId
photon:
  AppId:



---

spring:
  profiles:
    active: prod

---

spring:
  profiles:
    active: dev

---

spring:
  profiles:
    active: local

# 로컬 환경에서는 logback-spring-local.xml, 운영 환경에서는 logback-spring-dev.xml
logging:
  config: classpath:logback-spring-local.xml